export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Products } from './products/Products'
export { default as Login } from './login/login'
export { default as ProductDetail } from './productDetail/ProductDetail'